---
title: Review of some general Concepts
author: D. Miranda-Esquivel
date: 2024-01-20

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---


# General objective

- In this section, we will review:

-- basic probability concepts and various probability distributions.

-- use(s) of Bayes inference in Ecology

-- some critics ot the use of **p**


## Key Concepts

- Probability basics

- Common probability distributions (binomial, dirichlet, gamma, exponential, log-normal)

- Time to say good-bye to **p**

- Bayes in Ecology

## Activities 


- Review: Unit 3. Bodine et al and the ASA statement.

- Read: Bayesian inference in ecology. Ecology Letters (2004) 7: 509–520 doi: 10.1111/j.1461-0248.2004.00603.x

- Find a paper in your area of expertise and revise the use of *p*, write down a short analysis (max 1000 words) of the possible ways to solve the problems you might have detected.


## Readings


### Basic readings

- **Unit 3. Bodine et al** [Read Online](https://drive.google.com/file/d/1jtas7BKn0ZcJlQ3iobF8ReJ2Wc1BQJZd/view?usp=drive_link)

- **Ellison. 2004**. Bayesian inference in ecology. Ecology Letters. 7: 509–520 doi: 10.1111/j.1461-0248.2004.00603.x

- **ASA statement** [Read Online](https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1583913)


### Should read

- **Chapter 5. Sokal & Rohlf**

- **Chapter 1. Anderson's perspective on Science and Experimental design** [Read Online](https://drive.google.com/file/d/1Vng6xtgaa_wHkf0Wb1x48M9q5nS10HkJ/view?usp=sharing)

- **[Storopoli (2022). Bayesian Statistics: a graduate course.]**(https://github.com/storopoli/Bayesian-Statistics/tree/main)

- **[van de Schoot, R., Depaoli, S., King, R. et al. Bayesian statistics and modelling. Nat Rev Methods Primers 1, 1 (2021).]( https://doi.org/10.1038/s43586-020-00001-2)

