
---
title: Bayesian Data Analysis Resources
date: 2024-01-20

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---


## Quarto Documentation

- [Quarto Documentation](https://r4ds.hadley.nz/quarto.html)

## Kruschke 2015

- [Kruschke's Bayesian Data Analysis in R (PDF)](https://nyu-cdsc.github.io/learningr/assets/kruschke_bayesian_in_R.pdf)
- [Author's Site](https://sites.google.com/site/doingbayesiandataanalysis/software-installation)
- [Original Course](https://jkkweb.sitehost.iu.edu/jkkteach/P533/#Overview)

## GitHub Repositories

- [GitHub for the book (misc. authors)](https://github.com/boboppie/kruschke-doing_bayesian_data_analysis)
- [Python Implementation](https://github.com/JWarmenhoven/DBDA-python)
- [TidyVerse Implementation](https://github.com/ASKurz/Doing-Bayesian-Data-Analysis-in-brms-and-the-tidyverse)

## Year 2021

- [Bayesian Analysis Reporting Guidelines](https://pubmed.ncbi.nlm.nih.gov/34400814/)

## Bayesian Data Analysis in Ecology with R and Stan

- **Authors:** Fränzi Korner-Nievergelt, Tobias Roth, Stefanie von Felten, Jerôme Guélat, Bettina Almasi, Pius Korner-Nievergelt
- [BDAEcology](https://tobiasroth.github.io/BDAEcology/)


##  Kentaro Matsuura (2023). Bayesian Statistical Modeling with Stan, R, and ... {Note: this is an interesting approach/book, in some instances is rather naive and quite relaxed, while in some instances is complex, and slow to follow}
-  [gitHub](https://github.com/MatsuuraKentaro/Bayesian_Statistical_Modeling_with_Stan_R_and_Python) 



## Statistical rethinking

[site](https://xcelab.net/rm/statistical-rethinking/)
[Julia code](https://shmuma.github.io/rethinking-2ed-julia/)
[Videos](https://www.youtube.com/playlist?list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus)


## MacCarthy 
[Preface](https://assets.cambridge.org/97805216/15594/frontmatter/9780521615594_frontmatter.pdf)


##  Josh Cook
[site](https://github.com/jhrcook/bayesian-data-analysis-course)
[site](https://github.com/jhrcook/statistical-rethinking)
