---
title: Bayesian analysis 
author: D. Miranda-Esquivel
date: 2024-01-20

format:
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
---


# Review of Basic Probability Concepts

## Objectives

- Review basic probability concepts and distributions (binomial, dirichlet, gamma, exponential, logNormal), NP.

## Readings

- **Bodine et al Unit 3**
- **Sokal & Rohlf Chapter 5**
- **Anderson**
- **ASA statement** [Read Online](https://www.tandfonline.com/doi/full/10.1080/00031305.2019.1583913)

# Probability Concepts in Kruschke

## Chapter 2/4: Probability Kruschke

# Probability Topics

- Conditional Probability

# Statistical Concepts

- Likelihood

# Bayesian Analysis by Kruschke

## Chapter 5: Bayes Kruschke

### Classical Statistics in Bayesian Mode

# Monte Carlo Methods

## Chapter 7: MC Kruschke

# Modeling in Kruschke

## Chapters 9/10: Modelado Kruschke

Texts to reference: @kruschke2015doing

# Additional/Complementary Readings

- [Doing Bayesian Data Analysis in brms and the tidyverse. Version 1.1.0. A Solomon Kurz](https://bookdown.org/content/3686/)

# Bibliography

- @kruschke2015doing :: [Elsevier](https://shop.elsevier.com/books/doing-bayesian-data-analysis/kruschke/978-0-12-405888-0)
- [What's New in 2nd Edition](https://sites.google.com/site/doingbayesiandataanalysis/what-s-new-in-2nd-ed)

# Software

- [R - http://www.r-project.org/](http://www.r-project.org/)
- Julia https://julialang.org/

